export const DUMMY_USERS = [
  {
    user_id: 1,
    first_name: 'John',
    last_name: 'Doe',
    email: 'john@example.com',
    hashed_password: 'password123',
    phone_number: null,
    role: 'user',
    premium_start: null,
    premium_end: null,
    suspended: false,
  },
  {
    user_id: 2,
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane@example.com',
    hashed_password: 'password123',
    phone_number: null,
    role: 'admin',
    premium_start: null,
    premium_end: null,
    suspended: false,
  },
];