// constants/motivationalQuotes.ts

export const MOTIVATIONAL_QUOTES = [
  "Every healthy choice is a step toward the best version of you! 🌟",
  "You didn't come this far to only come this far. Keep going! 💪",
  "Small progress is still progress. You're doing amazing! 🏆",
  "Your body deserves love and nourishment today! 🥗",
  "Drink water, eat well, move your body. You've got this! 💧",
  "Consistency beats perfection every single time. 🎯",
  "One meal at a time, one day at a time. You're doing great! 🍽️",
  "Your health is an investment, not an expense. 💚",
  "Progress, not perfection. Keep showing up! 🌱",
  "Every workout counts, even the short ones. 🏃",
  "Fuel your body like it deserves the best! 🥦",
  "You are stronger than your cravings. Stay the course! 💪",
  "Hydration is self-care. Drink that water! 💧",
  "A healthy outside starts from the inside. 🌿",
  "You've got the power to change your story today! ✨",
  "Don't stop until you're proud. Keep going! 🏅",
  "Small steps every day lead to big changes. 🚶",
  "Believe in yourself — your body is capable of amazing things! 🌟",
  "Nourish to flourish. Every bite matters! 🥗",
  "Rest, recover, repeat. You deserve it! 😴",
  "Today's effort is tomorrow's result. Stay consistent! 📈",
  "You are what you eat — so eat something amazing! 🍎",
  "Celebrate every win, no matter how small! 🎉",
  "Your journey is unique. Own it! 🦋",
  "Healthy habits today, happier you tomorrow! 🌅",
  "Energy flows where intention goes. Set yours high! ⚡",
  "You're not just losing weight, you're gaining life! 💚",
  "Make yourself a priority — you deserve it! 👑",
  "Every healthy meal is an act of self-love. 🥰",
  "New day, new chance to be your best self! 🌈",
];