"""add nutritionist features

Revision ID: 006bf1e34d58
Revises: c5a12fb5ff8c
Create Date: 2026-04-30 16:30:37.981247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '006bf1e34d58'
down_revision: Union[str, None] = 'c5a12fb5ff8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'nutritionist'")
    
    op.create_table('nutritionist_profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialisation', sa.String(), nullable=False),
    sa.Column('credentials', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.Column('filters', sa.String(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.Column('diary_feedback', sa.String(), nullable=True),
    sa.Column('testimonial', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_nutritionist_profile_user_id'), 'nutritionist_profile', ['user_id'], unique=True)
    op.create_table('analysis',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('nutritionist_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('nutritionist_name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('went_well', sa.String(), nullable=False),
    sa.Column('areas_to_improve', sa.String(), nullable=False),
    sa.Column('recommendations', sa.String(), nullable=False),
    sa.Column('next_steps', sa.String(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nutritionist_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_analysis_client_id'), 'analysis', ['client_id'], unique=False)
    op.create_index(op.f('ix_analysis_nutritionist_id'), 'analysis', ['nutritionist_id'], unique=False)
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nutritionist_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'declined', 'cancelled', name='bookingstatus'), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nutritionist_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_booking_nutritionist_id'), 'booking', ['nutritionist_id'], unique=False)
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    op.create_table('nutrition_content',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('article', 'tip', 'advice', name='nutritioncontenttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_nutrition_content_author_id'), 'nutrition_content', ['author_id'], unique=False)
    op.create_table('nutritionist_availability_slot',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('nutritionist_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('slot_time', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nutritionist_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_index(op.f('ix_nutritionist_availability_slot_nutritionist_id'), 'nutritionist_availability_slot', ['nutritionist_id'], unique=False)
    op.create_table('chat',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nutritionist_id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('reported', sa.Boolean(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nutritionist_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chat_booking_id'), 'chat', ['booking_id'], unique=False)
    op.create_index(op.f('ix_chat_nutritionist_id'), 'chat', ['nutritionist_id'], unique=False)
    op.create_index(op.f('ix_chat_user_id'), 'chat', ['user_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chat_message_chat_id'), 'chat_message', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_message_sender_id'), 'chat_message', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_sender_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_chat_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_chat_user_id'), table_name='chat')
    op.drop_index(op.f('ix_chat_nutritionist_id'), table_name='chat')
    op.drop_index(op.f('ix_chat_booking_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_nutritionist_availability_slot_nutritionist_id'), table_name='nutritionist_availability_slot')
    op.drop_table('nutritionist_availability_slot')
    op.drop_index(op.f('ix_nutrition_content_author_id'), table_name='nutrition_content')
    op.drop_table('nutrition_content')
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_nutritionist_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_analysis_nutritionist_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_client_id'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_index(op.f('ix_nutritionist_profile_user_id'), table_name='nutritionist_profile')
    op.drop_table('nutritionist_profile')
    # ### end Alembic commands ###
