"""add_meal_type_to_recipe_table

Revision ID: 22bcecf42264
Revises: f3b9024f4adf
Create Date: 2026-04-09 17:20:55.797228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22bcecf42264'
down_revision: Union[str, None] = 'f3b9024f4adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', name='mealtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'meal_type')
    # ### end Alembic commands ###
