"""add admin performance integrations export tables

Revision ID: 2ec7e66ec0ab
Revises: 006bf1e34d58
Create Date: 2026-05-01 08:32:45.152088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ec7e66ec0ab'
down_revision: Union[str, None] = '006bf1e34d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spoonacular_api_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_spoonacular_api_log_created_at'), 'spoonacular_api_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_spoonacular_api_log_endpoint'), 'spoonacular_api_log', ['endpoint'], unique=False)
    op.create_index(op.f('ix_spoonacular_api_log_food_name'), 'spoonacular_api_log', ['food_name'], unique=False)
    op.create_index(op.f('ix_spoonacular_api_log_success'), 'spoonacular_api_log', ['success'], unique=False)
    op.create_table('app_event_log',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature', sa.Enum('meal_logger', 'goals', 'recommend_meal', 'consult', 'progress_report', 'my_meals', name='appfeature'), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_app_event_log_event_name'), 'app_event_log', ['event_name'], unique=False)
    op.create_index(op.f('ix_app_event_log_feature'), 'app_event_log', ['feature'], unique=False)
    op.create_index(op.f('ix_app_event_log_user_id'), 'app_event_log', ['user_id'], unique=False)
    op.create_table('export_history',
    sa.Column('export_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('export_range', sa.Enum('thirty_days', 'three_months', 'six_months', 'all', name='exportrange'), nullable=False),
    sa.Column('export_format', sa.Enum('csv', 'json', name='exportformat'), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_index(op.f('ix_export_history_created_at'), 'export_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_export_history_created_by_user_id'), 'export_history', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_export_history_expires_at'), 'export_history', ['expires_at'], unique=False)
    op.create_index(op.f('ix_export_history_token'), 'export_history', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_history_token'), table_name='export_history')
    op.drop_index(op.f('ix_export_history_expires_at'), table_name='export_history')
    op.drop_index(op.f('ix_export_history_created_by_user_id'), table_name='export_history')
    op.drop_index(op.f('ix_export_history_created_at'), table_name='export_history')
    op.drop_table('export_history')
    op.drop_index(op.f('ix_app_event_log_user_id'), table_name='app_event_log')
    op.drop_index(op.f('ix_app_event_log_feature'), table_name='app_event_log')
    op.drop_index(op.f('ix_app_event_log_event_name'), table_name='app_event_log')
    op.drop_table('app_event_log')
    op.drop_index(op.f('ix_spoonacular_api_log_success'), table_name='spoonacular_api_log')
    op.drop_index(op.f('ix_spoonacular_api_log_food_name'), table_name='spoonacular_api_log')
    op.drop_index(op.f('ix_spoonacular_api_log_endpoint'), table_name='spoonacular_api_log')
    op.drop_index(op.f('ix_spoonacular_api_log_created_at'), table_name='spoonacular_api_log')
    op.drop_table('spoonacular_api_log')
    # ### end Alembic commands ###
