"""add email verification fields

Revision ID: 4886ad635af9
Revises: 11be422e3956
Create Date: 2026-04-21 12:18:28.109590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4886ad635af9'
down_revision: Union[str, None] = '11be422e3956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect, text

    # --- dish_ingredient_lookup column adjustments ---
    # These alter_column calls are safe to run even if already correct;
    # PostgreSQL will no-op if the type is already as expected.
    op.alter_column('dish_ingredient_lookup', 'ingredients',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dish_ingredient_lookup', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)

    # Reason: constraint may not exist if table was created via create_all()
    # rather than via the d2588a94e03c migration. IF EXISTS makes this idempotent.
    op.execute(
        "ALTER TABLE dish_ingredient_lookup DROP CONSTRAINT IF EXISTS uq_dish_ingredient_lookup_dish_class"
    )

    # --- user column additions ---
    # Reason: columns may already exist if the schema was bootstrapped via
    # SQLModel.metadata.create_all() before migrations were stamped.
    # Using ADD COLUMN IF NOT EXISTS makes each step idempotent.
    op.execute(
        'ALTER TABLE "user" ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT false'
    )
    op.execute(
        'ALTER TABLE "user" ADD COLUMN IF NOT EXISTS verification_code VARCHAR'
    )
    op.execute(
        'ALTER TABLE "user" ADD COLUMN IF NOT EXISTS verification_code_expires_at TIMESTAMP WITH TIME ZONE'
    )

    # Backfill: mark all existing users as verified so no one is locked out.
    op.execute('UPDATE "user" SET email_verified = true')

    # Remove the bootstrap default now that backfill is complete.
    op.alter_column('user', 'email_verified', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code_expires_at')
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'email_verified')
    op.create_unique_constraint(op.f('uq_dish_ingredient_lookup_dish_class'), 'dish_ingredient_lookup', ['dish_class'], postgresql_nulls_not_distinct=False)
    op.alter_column('dish_ingredient_lookup', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('dish_ingredient_lookup', 'ingredients',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
