"""add email verification fields

Revision ID: 4886ad635af9
Revises: 11be422e3956
Create Date: 2026-04-21 12:18:28.109590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4886ad635af9'
down_revision: Union[str, None] = '11be422e3956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish_ingredient_lookup', 'ingredients',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dish_ingredient_lookup', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_dish_ingredient_lookup_dish_class'), 'dish_ingredient_lookup', type_='unique')

    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('verification_code_expires_at', 
                                    existing_type=postgresql.TIMESTAMP(),
                                    type_=sa.DateTime(timezone=True),
                                    existing_nullable=True))

    op.execute('UPDATE "user" SET email_verified = true')

    op.alter_column('user', 'email_verified', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code_expires_at')
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'email_verified')
    op.create_unique_constraint(op.f('uq_dish_ingredient_lookup_dish_class'), 'dish_ingredient_lookup', ['dish_class'], postgresql_nulls_not_distinct=False)
    op.alter_column('dish_ingredient_lookup', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('dish_ingredient_lookup', 'ingredients',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
