"""add custom_meal and notification tables

Revision ID: 4e7cc07d55a1
Revises: 781bc367f2d2
Create Date: 2026-04-23 16:24:51.464748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7cc07d55a1'
down_revision: Union[str, None] = '781bc367f2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE foodsource ADD VALUE IF NOT EXISTS 'custom'")
    op.execute("ALTER TYPE foodsource ADD VALUE IF NOT EXISTS 'admin'")
    
    op.create_table('custom_meal',
    sa.Column('custom_meal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('emoji_bg', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('serving_unit', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('custom_meal_id')
    )
    op.create_index(op.f('ix_custom_meal_name'), 'custom_meal', ['name'], unique=False)
    op.create_index(op.f('ix_custom_meal_user_id'), 'custom_meal', ['user_id'], unique=False)
    op.create_table('notification_history',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('segment', sa.Enum('all', 'freemium', 'premium', name='notificationsegment'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_history_created_by_user_id'), 'notification_history', ['created_by_user_id'], unique=False)
    op.create_table('push_token',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_push_token_token'), 'push_token', ['token'], unique=True)
    op.create_index(op.f('ix_push_token_user_id'), 'push_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_token_user_id'), table_name='push_token')
    op.drop_index(op.f('ix_push_token_token'), table_name='push_token')
    op.drop_table('push_token')
    op.drop_index(op.f('ix_notification_history_created_by_user_id'), table_name='notification_history')
    op.drop_table('notification_history')
    op.drop_index(op.f('ix_custom_meal_user_id'), table_name='custom_meal')
    op.drop_index(op.f('ix_custom_meal_name'), table_name='custom_meal')
    op.drop_table('custom_meal')
    # ### end Alembic commands ###
