"""add user subscription and update user role model

Revision ID: 5efbdf245c58
Revises: 837cbf4a62d4
Create Date: 2026-04-19 13:37:55.007714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efbdf245c58'
down_revision: Union[str, None] = '837cbf4a62d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscription',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('monthly', 'annual', name='subscriptionplan'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', name='subscriptionstatus'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_user_subscription_user_id'), 'user_subscription', ['user_id'], unique=False)
    op.drop_constraint(op.f('dietary_entry_user_id_fkey'), 'dietary_entry', type_='foreignkey')
    op.create_foreign_key(None, 'dietary_entry', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dietary_goal_user_id_fkey'), 'dietary_goal', type_='foreignkey')
    op.create_foreign_key(None, 'dietary_goal', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('meal_user_id_fkey'), 'meal', type_='foreignkey')
    op.create_foreign_key(None, 'meal', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('recipe_user_id_fkey'), 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('recommendation_log_user_id_fkey'), 'recommendation_log', type_='foreignkey')
    op.drop_constraint(op.f('fk_recommendation_log_recipe_id'), 'recommendation_log', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation_log', 'recipe', ['recipe_id'], ['recipe_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recommendation_log', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_preferences_user_id_fkey'), 'user_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'user_preferences', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_profile_user_id_fkey'), 'user_profile', type_='foreignkey')
    op.create_foreign_key(None, 'user_profile', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('water_intake_log_user_id_fkey'), 'water_intake_log', type_='foreignkey')
    op.create_foreign_key(None, 'water_intake_log', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('weight_log_user_id_fkey'), 'weight_log', type_='foreignkey')
    op.create_foreign_key(None, 'weight_log', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weight_log', type_='foreignkey')
    op.create_foreign_key(op.f('weight_log_user_id_fkey'), 'weight_log', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'water_intake_log', type_='foreignkey')
    op.create_foreign_key(op.f('water_intake_log_user_id_fkey'), 'water_intake_log', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.create_foreign_key(op.f('user_profile_user_id_fkey'), 'user_profile', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'user_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('user_preferences_user_id_fkey'), 'user_preferences', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'recommendation_log', type_='foreignkey')
    op.drop_constraint(None, 'recommendation_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_recommendation_log_recipe_id'), 'recommendation_log', 'recipe', ['recipe_id'], ['recipe_id'])
    op.create_foreign_key(op.f('recommendation_log_user_id_fkey'), 'recommendation_log', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_user_id_fkey'), 'recipe', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'meal', type_='foreignkey')
    op.create_foreign_key(op.f('meal_user_id_fkey'), 'meal', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'dietary_goal', type_='foreignkey')
    op.create_foreign_key(op.f('dietary_goal_user_id_fkey'), 'dietary_goal', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'dietary_entry', type_='foreignkey')
    op.create_foreign_key(op.f('dietary_entry_user_id_fkey'), 'dietary_entry', 'user', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_user_subscription_user_id'), table_name='user_subscription')
    op.drop_table('user_subscription')
    # ### end Alembic commands ###
