"""Update User user_id default to None instead of 1

Revision ID: 6eb12d98aca4
Revises: 
Create Date: 2026-03-11 11:37:49.674681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb12d98aca4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('ALTER TABLE "user" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY')


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('ALTER TABLE "user" ALTER COLUMN user_id DROP IDENTITY IF EXISTS')
