"""add support tickets and subscription transactions

Revision ID: 781bc367f2d2
Revises: 869ab49f9f6a
Create Date: 2026-04-21 21:44:43.434410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '781bc367f2d2'
down_revision: Union[str, None] = '869ab49f9f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='supportticketstatus'), nullable=False),
    sa.Column('admin_reply', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_support_ticket_user_id'), 'support_ticket', ['user_id'], unique=False)
    op.create_table('subscription_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('checkout', 'cancel', name='subscriptiontransactiontype'), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='subscriptiontransactionstatus'), nullable=False),
    sa.Column('plan', postgresql.ENUM('monthly', 'annual', name='subscriptionplan', create_type=False), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_provider', sa.String(), nullable=True),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscription.subscription_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_subscription_transaction_subscription_id'), 'subscription_transaction', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_transaction_user_id'), 'subscription_transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_transaction_user_id'), table_name='subscription_transaction')
    op.drop_index(op.f('ix_subscription_transaction_subscription_id'), table_name='subscription_transaction')
    op.drop_table('subscription_transaction')
    op.drop_index(op.f('ix_support_ticket_user_id'), table_name='support_ticket')
    op.drop_table('support_ticket')
    # ### end Alembic commands ###
