"""add is_favorite to meal and remove favourite meal tables

Revision ID: 837cbf4a62d4
Revises: dbd88f14f82c
Create Date: 2026-04-16 13:22:35.854484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '837cbf4a62d4'
down_revision: Union[str, None] = 'dbd88f14f82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourite_meal_item_favourite_meal_id'), table_name='favourite_meal_item')
    op.drop_index(op.f('ix_favourite_meal_item_food_id'), table_name='favourite_meal_item')
    op.drop_table('favourite_meal_item')
    op.drop_index(op.f('ix_favourite_meal_user_id'), table_name='favourite_meal')
    op.drop_table('favourite_meal')

    op.add_column('meal', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'is_favorite')
    op.create_table('favourite_meal_item',
    sa.Column('favourite_meal_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('favourite_meal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favourite_meal_id'], ['favourite_meal.favourite_meal_id'], name=op.f('favourite_meal_item_favourite_meal_id_fkey')),
    sa.ForeignKeyConstraint(['food_id'], ['food_item.food_id'], name=op.f('favourite_meal_item_food_id_fkey')),
    sa.PrimaryKeyConstraint('favourite_meal_item_id', name=op.f('favourite_meal_item_pkey'))
    )
    op.create_index(op.f('ix_favourite_meal_item_food_id'), 'favourite_meal_item', ['food_id'], unique=False)
    op.create_index(op.f('ix_favourite_meal_item_favourite_meal_id'), 'favourite_meal_item', ['favourite_meal_id'], unique=False)
    op.create_table('favourite_meal',
    sa.Column('favourite_meal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meal_type', postgresql.ENUM('breakfast', 'lunch', 'dinner', name='mealtype'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('favourite_meal_user_id_fkey')),
    sa.PrimaryKeyConstraint('favourite_meal_id', name=op.f('favourite_meal_pkey'))
    )
    op.create_index(op.f('ix_favourite_meal_user_id'), 'favourite_meal', ['user_id'], unique=False)
    # ### end Alembic commands ###
