"""remove water intake log table

Revision ID: 84fa030355b4
Revises: 2ec7e66ec0ab
Create Date: 2026-05-15 22:12:17.156969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84fa030355b4'
down_revision: Union[str, None] = '2ec7e66ec0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_intake_log_user_id'), table_name='water_intake_log')
    op.drop_table('water_intake_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_intake_log',
    sa.Column('water_log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_ml', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('water_intake_log_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('water_log_id', name=op.f('water_intake_log_pkey'))
    )
    op.create_index(op.f('ix_water_intake_log_user_id'), 'water_intake_log', ['user_id'], unique=False)
    # ### end Alembic commands ###
