"""add external_id to food_item

Revision ID: 90d6ffb6d746
Revises: 624805f17e4d
Create Date: 2026-04-07 21:29:45.810653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d6ffb6d746'
down_revision: Union[str, None] = '624805f17e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_item', sa.Column('external_id', sa.Integer(), nullable=True))
    op.add_column('food_item', sa.Column('source', sa.Enum('product', 'ingredient', name='foodsource'), nullable=False))
    op.create_index(op.f('ix_food_item_external_id'), 'food_item', ['external_id'], unique=False)
    op.add_column('user_profile', sa.Column('dob', sa.Date(), nullable=True))
    op.drop_column('user_profile', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'dob')
    op.drop_index(op.f('ix_food_item_external_id'), table_name='food_item')
    op.drop_column('food_item', 'source')
    op.drop_column('food_item', 'external_id')
    # ### end Alembic commands ###
