"""add manual to foodsource enum

Revision ID: af0a46a77905
Revises: 90d6ffb6d746
Create Date: 2026-04-08 15:45:00.562578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0a46a77905'
down_revision: Union[str, None] = '90d6ffb6d746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_item', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_column('meal_item', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_item', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('meal_item', 'amount')
    # ### end Alembic commands ###
