"""add_tdee_column_in_user_profile_table

Revision ID: cb3de9faa253
Revises: 08c9cc617159
Create Date: 2026-04-03 12:23:24.667318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3de9faa253'
down_revision: Union[str, None] = '08c9cc617159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('tdee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'tdee')
    # ### end Alembic commands ###
