"""make user_id auto increment

Revision ID: cced55872ea7
Revises: de6ee1874cbe
Create Date: 2026-03-11 11:55:22.243523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cced55872ea7'
down_revision: Union[str, None] = 'de6ee1874cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('ALTER TABLE "user" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY')


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('ALTER TABLE "user" ALTER COLUMN user_id DROP IDENTITY IF EXISTS')
