"""refactor meal and remove meal_item, recipe_item

Revision ID: dbd88f14f82c
Revises: dd776a90249e
Create Date: 2026-04-16 12:36:54.220424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbd88f14f82c'
down_revision: Union[str, None] = 'dd776a90249e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_item_food_id'), table_name='meal_item')
    op.drop_index(op.f('ix_meal_item_meal_id'), table_name='meal_item')
    op.drop_table('meal_item')
    op.drop_index(op.f('ix_recipe_item_food_id'), table_name='recipe_item')
    op.drop_index(op.f('ix_recipe_item_recipe_id'), table_name='recipe_item')
    op.drop_table('recipe_item')
    op.add_column('meal', sa.Column('source', sa.Enum('ingredient', 'product', 'manual', name='foodsource'), nullable=True))
    op.add_column('meal', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('meal', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('meal', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('meal', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('meal', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('meal', sa.Column('protein_g', sa.Float(), nullable=True))
    op.add_column('meal', sa.Column('carb_g', sa.Float(), nullable=True))
    op.add_column('meal', sa.Column('fat_g', sa.Float(), nullable=True))
    op.add_column('meal', sa.Column('sugar_g', sa.Float(), nullable=True))
    op.add_column('meal', sa.Column('fiber_g', sa.Float(), nullable=True))
    op.add_column('meal', sa.Column('sodium_mg', sa.Float(), nullable=True))
    op.create_index(op.f('ix_meal_barcode'), 'meal', ['barcode'], unique=False)
    
    op.execute("""
        UPDATE meal
        SET source = 'manual'
        WHERE source IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET amount = 1
        WHERE amount IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET unit = 'serving'
        WHERE unit IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET calories = total_calories
        WHERE calories IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET protein_g = total_protein_g
        WHERE protein_g IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET carb_g = total_carb_g
        WHERE carb_g IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET fat_g = total_fat_g
        WHERE fat_g IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET sugar_g = total_sugar_g
        WHERE sugar_g IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET sodium_mg = total_sodium_mg
        WHERE sodium_mg IS NULL
    """)

    op.execute("""
        UPDATE meal
        SET fiber_g = 0
        WHERE fiber_g IS NULL
    """)

    op.alter_column('meal', 'source', existing_type=sa.Enum('ingredient', 'product', 'manual', name='foodsource'), nullable=False)
    op.alter_column('meal', 'amount', existing_type=sa.Float(), nullable=False)
    op.alter_column('meal', 'unit', existing_type=sa.String(), nullable=False)
    op.alter_column('meal', 'calories', existing_type=sa.Float(), nullable=False)
    op.alter_column('meal', 'protein_g', existing_type=sa.Float(), nullable=False)
    op.alter_column('meal', 'carb_g', existing_type=sa.Float(), nullable=False)
    op.alter_column('meal', 'fat_g', existing_type=sa.Float(), nullable=False)

    op.drop_column('meal', 'total_sugar_g')
    op.drop_column('meal', 'total_fat_g')
    op.drop_column('meal', 'total_protein_g')
    op.drop_column('meal', 'total_calories')
    op.drop_column('meal', 'total_sodium_mg')
    op.drop_column('meal', 'total_carb_g')
    op.drop_column('meal', 'meal_type')
    
    op.drop_constraint(op.f('uq_recipe_spoonacular_id'), 'recipe', type_='unique')
    op.drop_index(op.f('ix_recipe_spoonacular_id'), table_name='recipe')
    op.create_index(op.f('ix_recipe_spoonacular_id'), 'recipe', ['spoonacular_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_spoonacular_id'), table_name='recipe')
    op.create_index(op.f('ix_recipe_spoonacular_id'), 'recipe', ['spoonacular_id'], unique=False)
    op.create_unique_constraint(op.f('uq_recipe_spoonacular_id'), 'recipe', ['spoonacular_id'], postgresql_nulls_not_distinct=False)
    op.add_column('meal', sa.Column('meal_type', postgresql.ENUM('breakfast', 'lunch', 'dinner', name='mealtype'), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('total_carb_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('total_sodium_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('total_calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('total_protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('total_fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('total_sugar_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_meal_barcode'), table_name='meal')
    op.drop_column('meal', 'sodium_mg')
    op.drop_column('meal', 'fiber_g')
    op.drop_column('meal', 'sugar_g')
    op.drop_column('meal', 'fat_g')
    op.drop_column('meal', 'carb_g')
    op.drop_column('meal', 'protein_g')
    op.drop_column('meal', 'calories')
    op.drop_column('meal', 'unit')
    op.drop_column('meal', 'amount')
    op.drop_column('meal', 'barcode')
    op.drop_column('meal', 'brand')
    op.drop_column('meal', 'source')
    op.create_table('recipe_item',
    sa.Column('recipe_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_item.food_id'], name=op.f('recipe_item_food_id_fkey')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], name=op.f('recipe_item_recipe_id_fkey')),
    sa.PrimaryKeyConstraint('recipe_item_id', name=op.f('recipe_item_pkey'))
    )
    op.create_index(op.f('ix_recipe_item_recipe_id'), 'recipe_item', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_item_food_id'), 'recipe_item', ['food_id'], unique=False)
    op.create_table('meal_item',
    sa.Column('meal_item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('carb_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_item.food_id'], name=op.f('meal_item_food_id_fkey')),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.meal_id'], name=op.f('meal_item_meal_id_fkey')),
    sa.PrimaryKeyConstraint('meal_item_id', name=op.f('meal_item_pkey'))
    )
    op.create_index(op.f('ix_meal_item_meal_id'), 'meal_item', ['meal_id'], unique=False)
    op.create_index(op.f('ix_meal_item_food_id'), 'meal_item', ['food_id'], unique=False)
    # ### end Alembic commands ###
