"""add completed booking status

Revision ID: ee699a341082
Revises: f3dfe406138e
Create Date: 2026-05-17 19:03:21.101253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee699a341082'
down_revision: Union[str, None] = 'f3dfe406138e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analysis_client_id'), 'analysis', ['client_id'], unique=False)
    op.create_index(op.f('ix_analysis_nutritionist_id'), 'analysis', ['nutritionist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_nutritionist_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_client_id'), table_name='analysis')
    # ### end Alembic commands ###
