"""added meal_type to recipe table

Revision ID: f3b9024f4adf
Revises: 6958f372c62b
Create Date: 2026-04-09 17:01:08.473523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3b9024f4adf'
down_revision: Union[str, None] = '6958f372c62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=False)
    op.alter_column('user_profile', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user_profile', 'height_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_profile', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_profile', 'activity_level',
               existing_type=postgresql.ENUM('sedentary', 'lightly_active', 'active', 'very_active', name='activitylevel'),
               nullable=False)
    op.alter_column('user_profile', 'tdee',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'tdee',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_profile', 'activity_level',
               existing_type=postgresql.ENUM('sedentary', 'lightly_active', 'active', 'very_active', name='activitylevel'),
               nullable=True)
    op.alter_column('user_profile', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_profile', 'height_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_profile', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user_profile', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=True)
    # ### end Alembic commands ###
