"""change analysis id to integer

Revision ID: f3dfe406138e
Revises: 84fa030355b4
Create Date: 2026-05-17 16:05:09.473898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3dfe406138e'
down_revision: Union[str, None] = '84fa030355b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis")

    op.create_table(
        "analysis",
        sa.Column("analysis_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("nutritionist_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("nutritionist_name", sa.String(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("went_well", sa.String(), nullable=False),
        sa.Column("areas_to_improve", sa.String(), nullable=False),
        sa.Column("recommendations", sa.String(), nullable=False),
        sa.Column("next_steps", sa.String(), nullable=False),
        sa.Column("last_updated", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["nutritionist_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["user.user_id"], ondelete="SET NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis")

    op.create_table(
        "analysis",
        sa.Column("analysis_id", sa.String(), primary_key=True),
        sa.Column("nutritionist_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("nutritionist_name", sa.String(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("went_well", sa.String(), nullable=False),
        sa.Column("areas_to_improve", sa.String(), nullable=False),
        sa.Column("recommendations", sa.String(), nullable=False),
        sa.Column("next_steps", sa.String(), nullable=False),
        sa.Column("last_updated", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["nutritionist_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["user.user_id"], ondelete="SET NULL"),
    )
    # ### end Alembic commands ###
