import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#EDEAE4' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 24, paddingVertical: 12, gap: 12 },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  backArrow: { fontSize: 18, color: '#1A1814' },
  backText: { fontSize: 14, color: '#1A1814', fontWeight: '500' },
  progressRow: { flex: 1, flexDirection: 'row', gap: 4, alignItems: 'center' },
  progressDot: { flex: 1, height: 4, borderRadius: 2, backgroundColor: '#D0CBC3' },
  progressDotDone: { backgroundColor: '#2D5A3D' },
  stepCount: { fontSize: 12, color: '#8C6B2F', fontWeight: '600', minWidth: 28, textAlign: 'right' },
  scroll: { paddingHorizontal: 24, paddingBottom: 24 },
  footer: { paddingHorizontal: 24, paddingBottom: 16, paddingTop: 8 },
  stepContainer: { paddingTop: 8, gap: 20 },
  stepTitle: { fontSize: 26, fontWeight: '700', color: '#1A1814', lineHeight: 32 },
  stepSubtitle: { fontSize: 14, color: '#6B6560', lineHeight: 20, marginTop: -12 },
  highlight: { color: '#2D5A3D', fontWeight: '600' },
  fieldGroup: { gap: 8 },
  label: { fontSize: 13, fontWeight: '600', color: '#1A1814', textTransform: 'uppercase', letterSpacing: 0.5 },
  hint: { fontSize: 12, color: '#8C6B2F', lineHeight: 18 },
  input: { backgroundColor: '#F5F2ED', borderRadius: 10, borderWidth: 1, borderColor: '#D0CBC3', paddingVertical: 14, paddingHorizontal: 16, fontSize: 16, color: '#1A1814' },
  inputFlex: { flex: 1 },
  inputError: { borderColor: '#C8522A', backgroundColor: '#FDF0EC' },
  inputWithUnit: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  unit: { fontSize: 14, color: '#6B6560', fontWeight: '500', minWidth: 36 },
  errorText: { fontSize: 12, color: '#C8522A', marginTop: 2 },
  toggleRow: { flexDirection: 'row', gap: 10 },
  toggleBtn: { flex: 1, paddingVertical: 14, borderRadius: 10, borderWidth: 1.5, borderColor: '#D0CBC3', backgroundColor: '#F5F2ED', alignItems: 'center' },
  toggleBtnActive: { borderColor: '#2D5A3D', backgroundColor: '#EAF2EC' },
  toggleText: { fontSize: 15, color: '#6B6560', fontWeight: '500' },
  toggleTextActive: { color: '#2D5A3D', fontWeight: '700' },
  optionCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F5F2ED', borderRadius: 12, borderWidth: 1.5, borderColor: '#D0CBC3', padding: 14, gap: 12 },
  optionCardActive: { borderColor: '#2D5A3D', backgroundColor: '#EAF2EC' },
  optionEmoji: { fontSize: 24 },
  optionTextGroup: { flex: 1, gap: 2 },
  optionLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  optionLabel: { fontSize: 15, fontWeight: '600', color: '#1A1814' },
  optionLabelActive: { color: '#2D5A3D' },
  optionDesc: { fontSize: 12, color: '#6B6560', lineHeight: 17 },
  radioOuter: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#D0CBC3', alignItems: 'center', justifyContent: 'center' },
  radioOuterActive: { borderColor: '#2D5A3D' },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#2D5A3D' },
  recommendedBadge: { backgroundColor: '#2D5A3D', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2 },
  recommendedText: { fontSize: 10, color: '#FFFFFF', fontWeight: '600' },
  multiplierBadge: { fontSize: 12, color: '#8C6B2F', fontWeight: '700' },
  diffBadge: { backgroundColor: '#EAF2EC', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, alignSelf: 'flex-start', marginTop: 4 },
  diffText: { fontSize: 14, color: '#2D5A3D', fontWeight: '600' },
  cardioGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  cardioBtn: { width: (width - 48 - 30) / 4, paddingVertical: 14, borderRadius: 10, borderWidth: 1.5, borderColor: '#D0CBC3', backgroundColor: '#F5F2ED', alignItems: 'center' },
  cardioBtnActive: { borderColor: '#2D5A3D', backgroundColor: '#EAF2EC' },
  cardioText: { fontSize: 15, color: '#6B6560', fontWeight: '600' },
  cardioTextActive: { color: '#2D5A3D' },
  allergyGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  allergyChip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, borderWidth: 1.5, borderColor: '#D0CBC3', backgroundColor: '#F5F2ED' },
  allergyChipActive: { borderColor: '#C8522A', backgroundColor: '#FDF0EC' },
  allergyText: { fontSize: 13, color: '#6B6560', fontWeight: '500' },
  allergyTextActive: { color: '#C8522A', fontWeight: '600' },
  checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: '#D0CBC3', alignItems: 'center', justifyContent: 'center' },
  checkboxChecked: { backgroundColor: '#2D5A3D', borderColor: '#2D5A3D' },
  checkmark: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  btnPrimary: { backgroundColor: '#2D5A3D', borderRadius: 12, paddingVertical: 16, alignItems: 'center' },
  btnPrimaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', letterSpacing: 0.3 },
});